# Generated by Django 4.1.3 on 2022-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('physics', 'physics'), ('web-development', 'web-development'), ('programming', 'programming')], max_length=20),
        ),
    ]
