# Generated by Django 4.1.3 on 2022-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_date_posted_post_dateposted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('physics', 'physics'), ('web_development', 'web_development'), ('programming', 'programming'), ('personality', 'personality')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='posturl',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
