# Generated by Django 4.1.3 on 2022-12-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
