# Generated by Django 4.1.3 on 2022-12-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_posturl_alter_post_text_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='postitem',
        ),
    ]
