# Generated by Django 4.1.3 on 2022-12-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_post_postcomment_postitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('physics', 'physics'), ('web_development', 'web_development'), ('programming', 'programming'), ('personality', 'personality'), ('politics', 'politics')], max_length=20),
        ),
    ]
