# Generated by Django 4.1.3 on 2022-12-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('physics', 'physics'), ('web_development', 'web_development'), ('programming', 'programming'), ('personality', 'personality'), ('politics', 'politics'), ('football', 'football')], max_length=20),
        ),
    ]
