# Generated by Django 4.1.3 on 2023-01-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
