# Generated by Django 2.1 on 2022-12-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20221202_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='userimage/def.jpg', null=True, upload_to='userimage'),
        ),
    ]
